/* Poblar la Base de Datos */
/* Tabla: FACULTAD */
insert into Departamento values ('05', 'ANTIOQUIA');
insert into Departamento values ('08', 'ATLÁNTICO');
insert into Departamento values ('11', 'BOGOTÁ, D.C.');
insert into Departamento values ('13', 'BOLÍVAR');
insert into Departamento values ('15', 'BOYACÁ');
insert into Departamento values ('17', 'CALDAS');
insert into Departamento values ('18', 'CAQUETÁ');
insert into Departamento values ('19', 'CAUCA');
insert into Departamento values ('20', 'CESAR');
insert into Departamento values ('23', 'CÓRDOBA');
insert into Departamento values ('25', 'CUNDINAMARCA');
insert into Departamento values ('27', 'CHOCÓ');
insert into Departamento values ('41', 'HUILA');
insert into Departamento values ('44', 'LA GUAJIRA');
insert into Departamento values ('47', 'MAGDALENA');
insert into Departamento values ('50', 'META');
insert into Departamento values ('52', 'NARIÑO');
insert into Departamento values ('54', 'NORTE DE SANTANDER');
insert into Departamento values ('63', 'QUINDIO');
insert into Departamento values ('66', 'RISARALDA');
insert into Departamento values ('68', 'SANTANDER');
insert into Departamento values ('70', 'SUCRE');
insert into Departamento values ('73', 'TOLIMA');
insert into Departamento values ('76', 'VALLE DEL CAUCA');
insert into Departamento values ('81', 'ARAUCA');
insert into Departamento values ('85', 'CASANARE');
insert into Departamento values ('86', 'PUTUMAYO');
insert into Departamento values ('88', 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA');
insert into Departamento values ('91', 'AMAZONAS');
insert into Departamento values ('94', 'GUAINÍA');
insert into Departamento values ('95', 'GUAVIARE');
insert into Departamento values ('97', 'VAUPÉS');
insert into Departamento values ('99', 'VICHADA');
